#!/usr/bin/env python3
"""Generate AI_LOG.md from Claude Code session transcripts for this project.

Claude Code stores one JSONL transcript per session under
~/.claude/projects/<encoded-project-path>/. This script extracts every
human-typed prompt from those transcripts and writes a markdown log,
grouped by session, for inclusion with the homework deliverables.

Usage: python3 scripts/generate_ai_log.py
"""

import json
from datetime import datetime, timezone
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
TRANSCRIPT_DIR = (
    Path.home()
    / ".claude"
    / "projects"
    / str(PROJECT_DIR).replace("/", "-")
)
OUTPUT = PROJECT_DIR / "AI_LOG.md"

# Editor/context notices injected around prompts, not typed by the user.
SKIP_PREFIXES = ("<ide_opened_file>", "<ide_selection>", "<system-reminder>")

# Prompts before this moment were tooling setup (building this log script),
# not homework work, and are excluded.
START_AFTER = "2026-08-19T19:28:56Z"


def is_log_maintenance(text):
    """Prompts that just ask to update this log are noise, not homework work."""
    normalized = text.lower().replace("_", " ").replace(".md", "")
    return "ai log" in normalized


def extract_session(path: Path):
    title = None
    prompts = []  # (timestamp, text)
    for line in path.read_text().splitlines():
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        if obj.get("type") == "ai-title":
            title = obj.get("aiTitle") or title
        if obj.get("type") != "user":
            continue
        if obj.get("origin", {}).get("kind") != "human":
            continue  # tool results and synthetic messages
        content = obj.get("message", {}).get("content")
        if isinstance(content, str):
            texts = [content]
        else:
            texts = [
                c.get("text", "")
                for c in content or []
                if c.get("type") == "text"
            ]
        typed = [
            t.strip()
            for t in texts
            if t.strip() and not t.strip().startswith(SKIP_PREFIXES)
        ]
        if typed and any(is_log_maintenance(t) for t in typed):
            continue
        if typed and obj.get("timestamp", "") > START_AFTER:
            prompts.append((obj.get("timestamp", ""), "\n".join(typed)))
    return title, prompts


def main():
    sessions = sorted(TRANSCRIPT_DIR.glob("*.jsonl"))
    lines = [
        "# AI Usage Log",
        "",
        "All AI assistance for this project was done with Claude Code "
        "(Anthropic) inside the IDE. Below is every prompt I typed, grouped "
        "by session, extracted from the local session transcripts. "
        f"Generated by `scripts/generate_ai_log.py` on "
        f"{datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC.",
        "",
    ]
    total = 0
    # chronological by first prompt, not by transcript filename (a UUID)
    extracted = sorted(
        ((path, *extract_session(path)) for path in sessions),
        key=lambda session: session[2][0][0] if session[2] else "",
    )
    for path, title, prompts in extracted:
        if not prompts:
            continue
        started = prompts[0][0][:16].replace("T", " ")
        heading = title or f"Session {path.stem[:8]}"
        lines += [f"## {heading} — started {started} UTC", ""]
        for ts, text in prompts:
            when = ts[11:16] if len(ts) >= 16 else ""
            block = text if "\n" not in text else "\n> ".join(text.splitlines())
            lines.append(f"- **{when}** — {block}")
        lines.append("")
        total += len(prompts)
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT} ({total} prompts across "
          f"{sum(1 for _ in sessions)} session file(s))")


if __name__ == "__main__":
    main()
